title: UEB Teaching
description: Statistics & Bioinformatic Unit teaching website
show_downloads: true
theme: jekyll-theme-cayman
url: EduCaballero.github.io

# Social Media
twitter_username: Bioinfodotca
github_username:  bioinformatics-ca

# Build settings
markdown: kramdown

# Google Services
google_analytics: